# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "llm";
  version = "0.0.83";
  hash = "sha512-mrezwrda5BVMHqrPvnkyXbnDOiYPoKQWSJ/h0w46w7eqGzakeSyumVJG3+328B2xBQDWkgQsyvEAFpVJMMUOJg==";
  passthru = _finalAttrs: { };
  meta.description = "Large Language Model Plugin - The Scrypted LLM plugin allows connecting to various LLM providers, or running your own locally.";
}
