# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "nvr";
  version = "0.12.61";
  hash = "sha512-FrVVzmk1rDYbr1vI+hHRkmJTIke5JGkbWSq+84XAg8Qex3JWmNJVtFcjZgBZbksrwa6dsNdXKYo03J4TcNUSZQ==";
  passthru = _finalAttrs: { };
  meta.description = "Scrypted NVR - NVR plugin for Scrypted.";
}
