# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "nvr";
  version = "0.12.43";
  hash = "sha512-p+QYIgLMDB894hR3arpNRd3dy5rvEZ0TLBU/ZiGD52fnwkxv29X+7wrIJYb80ViRrrRaJw10fUlC1wiiZYQ6iA==";
  meta.description = "Scrypted NVR - NVR plugin for Scrypted.";
}
