# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "searxng-search";
  version = "0.0.3";
  hash = "sha512-Hxu70x7xXx19CkkMfa0+WE2cV/pbh61Y75ui1uy7noABRiuIHry5SUsSq+VWVffv7lExBUL74hIDsdLkHj0+JA==";
  passthru = _finalAttrs: { };
  meta.description = "SearXNG Web Search - Web search tool for LLMs using SearXNG with support for: * General web search * News search * Image search * Video search";
}
