# Auto-generated by update.sh - do not edit manually
{
  # Plugin version (@scrypted/openvino)
  version = "0.1.188";
  # npm integrity hash
  hash = "sha512-RAcBNL+ZQfesvV81vPu5Sj4VEG0728n+6SuJCDZl67Hyff6YeQvYwY9lcZ5msr1v/0vHhVck+Kyca1EBEEDs+w==";

  # OpenVINO Python package (from Scrypted requirements.txt)
  openvinoVersion = "2024.5.0";
  openvinoWheelBuild = "17288";
  openvinoHashes = {
    x86_64-linux = "sha256:a1b9de4ae4cd71dc9c2af53a7e347782dc9dd0ce469cf71aa3526daebe9e22bb";
    aarch64-linux = "sha256:3ead7bed64a32d7fa186e707acf8e4a79974d40fc750322ee36487c9c1171eed";
  };

  # openvino-telemetry dependency
  openvinoTelemetryVersion = "2025.2.0";
  openvinoTelemetryHash = "sha256-vLZn6DpE8gLs9M+kkoFxXG1+IUmdrsBP+FO3+WSDNZk=";

  # HuggingFace models (scrypted/plugin-models, openai/clip-vit-base-patch32, koushd/clip)
  modelsHash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
}
