# Auto-generated by update.sh - do not edit manually
{
  # Plugin version (@scrypted/openvino)
  version = "0.1.199";
  # npm integrity hash
  hash = "sha512-31Zkx8DtjFe3F6qDxqoIvpO3nGPrBOTgMp6VNbr5+4rMtaN0tm22Bay3YtMFPjYAKJVDMPvqb3jjFROCcbDrQQ==";

  # OpenVINO Python package (from Scrypted requirements.txt)
  openvinoVersion = "2024.5.0";
  openvinoWheelBuild = "17288";
  openvinoHashes = {
    x86_64-linux = "sha256:a1b9de4ae4cd71dc9c2af53a7e347782dc9dd0ce469cf71aa3526daebe9e22bb";
    aarch64-linux = "sha256:3ead7bed64a32d7fa186e707acf8e4a79974d40fc750322ee36487c9c1171eed";
  };

  # openvino-telemetry dependency
  openvinoTelemetryVersion = "2025.2.0";
  openvinoTelemetryHash = "sha256-vLZn6DpE8gLs9M+kkoFxXG1+IUmdrsBP+FO3+WSDNZk=";

  # numpy override (openvino 2024.5.0 requires numpy<2.2.0)
  numpyVersion = "2.1.3";
  numpyHashes = {
    x86_64-linux = "sha256:2312b2aa89e1f43ecea6da6ea9a810d06aae08321609d8dc0d0eda6d946a541b";
    aarch64-linux = "sha256:8637dcd2caa676e475503d1f8fdb327bc495554e10838019651b76d17b98e512";
  };
  numpyWheelPlatforms = {
    x86_64-linux = "manylinux_2_17_x86_64.manylinux2014_x86_64";
    aarch64-linux = "manylinux_2_17_aarch64.manylinux2014_aarch64";
  };

  # HuggingFace models (scrypted/plugin-models, openai/clip-vit-base-patch32, koushd/clip)
  modelsHash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
}
