# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "synology-ss";
  version = "0.0.17";
  hash = "sha512-R3ECJLnE2AGpOQgbX64w7AhCOgge03nI00CtnmSIbLXaYk+JY9pu15/O6a6CcW3eIMdKKI9iwH9KYCNRfywJwQ==";
  passthru = _finalAttrs: { };
  meta.description = "Synology Surveillance Station - A Synology Surveillance Station plugin for Scrypted";
}
