# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "snapshot";
  version = "0.2.68";
  hash = "sha512-ySpVcMf1XQgNYL8DtFN1FcrySYuNV+DbwJhzN67UOTNsNEYab3boGRD/zGHMnZ4WC9H6mnji1ZTi/om2CaIUMg==";
  passthru = _finalAttrs: { };
  meta.description = "Snapshot Plugin - Snapshot Plugin for Scrypted";
}
