# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "arlo-local";
  version = "0.6.0";
  hash = "sha512-x7LwT8bXX/QSPmqvrh31U8yzHbX0kpPvr5pD7Xws6hsxQTUag9hNayrnci2IFFUPPZPPqGPvSPhwpWWGaPjgLg==";
  meta.description = "Arlo Local Device Plugin - Arlo Local Plugin for Scrypted";
}
