# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "onvif";
  version = "0.1.31";
  hash = "sha512-wycKiRb+l8BBxMDw8d2OJKTmW6BT9gZxoAIxtPCUiZlkVLShr6wIFMhIH0VSICTOx0k0GBIaa0B6Z3x1/ybrnA==";
  meta.description = "ONVIF Camera Plugin - ONVIF Camera Plugin for Scrypted";
}
