# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "hue";
  version = "1.2.22";
  hash = "sha512-f+iBWoLovYxl69jscO0z2OqyB0jeG1aldNVFxR/zxE1RcXO5/v1gW2msWB14BMbcOBVZHXNUhZW1pLHUNapFVw==";
  passthru = _finalAttrs: { };
  meta.description = "Hue Bridge - A Philips Hue plugin for Scrypted";
}
