# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "sunrise-sunset";
  version = "0.0.4";
  hash = "sha512-0/0SayRg4DE3ZWtrzaQ5iUQpD/J9UzqXlO/mBhGHiALHteWkQI0WNuec3/b4rqkyW9he3FqES22Ki+pSJORxWQ==";
  meta.description = "Sunrise-Sunset Plugin - Sunrise-Sunset Sensors for Scrypted";
}
