# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "ring";
  version = "0.0.145";
  hash = "sha512-ygiONi11TPVW2n4BiJPnNw5OT04Bl0HWB5FZPvR/bFh5sTPmbrVYzzp5ZZc2gcisI7FPZVTOhS1qysvHz/HEDQ==";
  passthru = _finalAttrs: { };
  meta.description = "Ring Plugin - The Ring Plugin bridges compatible Ring Cameras in Scrypted to HomeKit.";
}
