# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "amcrest";
  version = "0.0.168";
  hash = "sha512-HjN/jN6mmRYHuxVSla/U+yBO+h+pdvwHxlCq/zryoPCfz5JwXZ/Y1La2Z3xFjuVKhsm3FgtmnwZs4H4MvLC6QA==";
  meta.description = "Amcrest Plugin - Amcrest Plugin for Scrypted";
}
