# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "google-cloud-tts";
  version = "0.0.23";
  hash = "sha512-656LCN7gcqhwx2cea72paUU5ii7J4l/zWM83lslNX4jwthTUcZwIWVtGQxwjngcnr5xGvMQh+ZGi9RmoNw044Q==";
  meta.description = "Google Cloud Text to Speech - Google Text to Speech plugin for Scrypted";
}
