# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "prebuffer-mixin";
  version = "0.10.66";
  hash = "sha512-UzhRscPQ6CkhKDmW3NEPT3Xi5YrNAnmY7GMxPHrdgbIpQzP5RO/TCbicLjYgLl8d2BYS1d3JlOvyFeX2V4DYYg==";
  passthru = _finalAttrs: { };
  meta.description = "Rebroadcast Plugin - Video Stream Rebroadcast, Prebuffer, and Management Plugin for Scrypted.";
}
