# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "prebuffer-mixin";
  version = "0.10.63";
  hash = "sha512-vNa4RWALK9HCdcwW4uEcbp0zWy9g7sCJ/ky02jjMzH23yzcS3XBpgDGGezqnypjWY8V8Q/QT3NrO6Xtpj+eZyA==";
  meta.description = "Rebroadcast Plugin - Video Stream Rebroadcast, Prebuffer, and Management Plugin for Scrypted.";
}
