# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "tapo";
  version = "0.0.22";
  hash = "sha512-+uxsC9RgCygsl2280w4nDKJgHCQhUdjh+hHzGxl3L2iQSSUoe5Y5Vxzo7MiC7dmG+AB+39+nqH60kEzUNxc4DA==";
  passthru = _finalAttrs: { };
  meta.description = "Tapo Camera Plugin - Tapo Camera Plugin for Scrypted";
}
