# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "smtp";
  version = "0.0.12";
  hash = "sha512-cpbZU+IAklpiU80MkNg79lQXXGyu9PzvfSYWqfNeY7SveZBFdWmDquRt6PACawPrIDU9WE49A7gCN0IsMfQW3g==";
  meta.description = "Mail (SMTP) Plugin - Mail (SMTP) for Scrypted. Turn devices on and off via a mail endpoint. Use in combination with the Dummy Switch plugin to create mail activated motion sensors.";
}
