# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "zwave";
  version = "0.1.10";
  hash = "sha512-N6zWK6uYSwi3htlc8poaT/K9L+cVoRhByFcZKvOiw1chvTbGpGKEIpKJ3bLD2y9C6jlNVoNU1LraJIklPDk8tQ==";
  meta.description = "Z-Wave Controller - Z-Wave USB Controller for Scrypted";
}
