# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "alexa";
  version = "0.3.7";
  hash = "sha512-TvD6tNXkUQHJgdFR9sA6sPqhRtFHPP4Sjvfp0bDYMyhwWlTkhwGxq057xZfcyGMnBlz36Ui0/NovU8S+uxFaQA==";
  passthru = _finalAttrs: { };
  meta.description = "Alexa - The Alexa Plugin lets you control your Scrypted devices from Amazon Alexa.";
}
