# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "pushover";
  version = "0.0.11";
  hash = "sha512-E39NU9M7Gl3VzGzkLwG5TFS0J+B9JvSGsT+NISY+kkVNkKlJBz4D35kmF2+O3R/RtdC4G+wGXKCIXSusGxzVyQ==";
  meta.description = "Pushover Plugin - 1. Install Pushover App. 2. Enter User Key and Token from Pushover.";
}
