# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "objectdetector";
  version = "0.1.77";
  hash = "sha512-xW/phUhU3KfFNCtbHO3hZApYBVzbjeAP/YUNIn3J5BUaFIS1SltXYZXRCaqdizb0SMeSM+RwlEfMKQGkBvvxwQ==";
  meta.description = "Video Analysis Plugin - Scrypted Video Analysis Plugin. Installed alongside a detection service like OpenCV or TensorFlow.";
}
