# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "unifi-protect";
  version = "0.0.165";
  hash = "sha512-82uahTT7G/ZVo0HSqa+1Nri+T5DUHk5wglfN5W+TK0NH5Bj96RyL9Uo3YJuCa34XIdoD/z8Z3Ij4rEEKXaDaHg==";
  meta.description = "Unifi Protect Plugin - Unifi Protect Plugin for Scrypted";
}
