# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: ctso <ctsoyars@gmail.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "wemo";
  version = "0.0.9";
  hash = "sha512-ubG5X7V1RnlVS/IQ/s4rnzqGuSVTK1QUificaZHH/EwRvHVozi1odVGAvm1uwFpWmgyQPNkhlb6fc1tS2N9IAw==";
  meta.description = "Wemo Controller - A Wemo plugin for Scrypted";
}
