# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "nanokvm";
  version = "0.0.7";
  hash = "sha512-T+OOG4ejWtoqNoeB+LbTTyh2Ik0RC1lPc6jDPhSADL62g9OqFpUT9l6N2y1OcvYG6G7GRgvUtVPET/MokyLZxQ==";
  meta.description = "NanoKVM - This plugin allows viewing and connecting to [NanoKVM](https://github.com/sipeed/NanoKVM) dongles from within the Scrypted Management Console.";
}
