# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "notifier-mixin";
  version = "0.1.28";
  hash = "sha512-oRIDyoEAYamyRInGgCFDATyH8L7t4G7qfE36QNmxonjyu+NGbfX1UJ5aMSVdTp0hT9LX8aCR0tbifKicOzfzcg==";
  meta.description = "Text to Speech Mixin for TVs and Speakers - Send notifications to smart speakers and smart displays using text to speech and text to image.";
}
