# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "lifx";
  version = "0.2.24";
  hash = "sha512-iu9Q66uRXJTlTjb23cH1BAd4zwOuraRH/rw2V3wR2tt7O4gzLzwijb4ufuuTjy+E+D+ecdLk+hMNb6Ma7s1zQg==";
  passthru = _finalAttrs: { };
  meta.description = "LIFX Controller - A Lifx plugin for Scrypted";
}
