# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "homeassistant";
  version = "0.1.16";
  hash = "sha512-jWXjC7o+Xr1e8kEr2YWIVSgwrYbmSQl1nYDJpt4dwLt+0bCV7fvDy2HrmhfvyOBhOUW31uhhkk2GSiDXbOftJQ==";
  passthru = _finalAttrs: { };
  meta.description = "Home Assistant - The Home Assistant Plugin for Scrypted imports `notify` services to be used within Scrypted.";
}
