#!/usr/bin/env bash
# plugins-update.sh - Fetches all @scrypted plugins from npm and generates package.nix files
#
# Usage: ./plugins-update.sh
#
# Generates plugins/<name>/package.nix for each auto-packaged plugin.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_DIR="$SCRIPT_DIR/plugins"

# Complex plugins with their own update.sh in plugins/<name>/
COMPLEX_PLUGINS=(
  "openvino"
)

# Plugins to skip or not yet integrated
IGNORED_PLUGINS=(
  # Python runtime plugins
  "arlo"
  "blink"
  "coreml"
  "kokoro"
  "ncnn"
  "notifier-zone-filter"
  "onnx"
  "opencv"
  "python-codecs"
  "rknn"
  "rockchip-essentials"
  "smtp-notifier"
  "tensorflow-lite" # deprecated
  "wyze"
  "x11-camera"
)

is_ignored() {
  local needle="$1"
  for item in "${IGNORED_PLUGINS[@]}"; do
    [[ "$item" == "$needle" ]] && return 0
  done
  return 1
}

is_complex() {
  local needle="$1"
  for item in "${COMPLEX_PLUGINS[@]}"; do
    [[ "$item" == "$needle" ]] && return 0
  done
  return 1
}

echo "Fetching plugin list from npm..."
mapfile -t PLUGINS < <(curl -s 'https://registry.npmjs.org/-/v1/search?text=keywords:scrypted&size=250' \
  | jq -r '.objects[].package.name' \
  | grep '^@scrypted/' \
  | sed 's/@scrypted\///' \
  | sort)

TOTAL=${#PLUGINS[@]}
echo "Found $TOTAL @scrypted/* packages"

GENERATED=0
DELEGATED=0
SKIPPED=0
ERRORS=0

for plugin in "${PLUGINS[@]}"; do
  if is_ignored "$plugin"; then
    echo "  [$plugin] Skipping"
    ((++SKIPPED))
    continue
  fi

  # Delegate to complex plugin's update.sh
  if is_complex "$plugin"; then
    echo "  [$plugin] Running plugins/$plugin/update.sh..."
    "$PLUGINS_DIR/$plugin/update.sh"
    ((++DELEGATED))
    continue
  fi

  printf "  [%s] Fetching... " "$plugin"

  DATA=$(curl -sS "https://registry.npmjs.org/@scrypted/$plugin/latest" 2>/dev/null) || DATA="{}"

  VERSION=$(echo "$DATA" | jq -r '.version // empty')
  HASH=$(echo "$DATA" | jq -r '.dist.integrity // empty')

  if [[ -z "$VERSION" ]] || [[ -z "$HASH" ]]; then
    echo "SKIP (missing data)"
    ((++ERRORS))
    continue
  fi

  # Extract metadata
  DESCRIPTION=$(echo "$DATA" | jq -r '.description // "Scrypted plugin"')
  SCRYPTED_NAME=$(echo "$DATA" | jq -r '.scrypted.name // empty')
  MAINTAINER_NAME=$(echo "$DATA" | jq -r '.maintainers[0].name // "unknown"')
  MAINTAINER_EMAIL=$(echo "$DATA" | jq -r '.maintainers[0].email // empty')

  # Build full description: "Scrypted NVR - NVR plugin for Scrypted."
  if [[ -n "$SCRYPTED_NAME" ]]; then
    FULL_DESC="$SCRYPTED_NAME - $DESCRIPTION"
  else
    FULL_DESC="$DESCRIPTION"
  fi

  # Build maintainer line
  if [[ -n "$MAINTAINER_EMAIL" ]]; then
    MAINTAINER_LINE="$MAINTAINER_NAME <$MAINTAINER_EMAIL>"
  else
    MAINTAINER_LINE="$MAINTAINER_NAME"
  fi

  echo "v$VERSION"

  PLUGIN_DIR="$PLUGINS_DIR/$plugin"
  mkdir -p "$PLUGIN_DIR"

  cat > "$PLUGIN_DIR/package.nix" << EOF
# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: $MAINTAINER_LINE
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "$plugin";
  version = "$VERSION";
  hash = "$HASH";
  passthru = _finalAttrs: { };
  meta.description = "$FULL_DESC";
}
EOF

  ((++GENERATED))
done

echo ""
echo "Summary: $GENERATED generated, $DELEGATED delegated, $SKIPPED ignored, $ERRORS errors"
echo ""
echo "Run 'git add packages/scrypted/plugins/' to track new files."
