# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "webrtc";
  version = "0.2.88";
  hash = "sha512-EdfAWPrPVM1HhjlB/FMlytlTbJf6BfQklzANPHfzDvurdtI4QkUzg2/IuCBjGIRQps4ZfJQb8OLEYzfUfKVy7A==";
  meta.description = "WebRTC Plugin - This plugin acts as a gateway for WebRTC clients and cameras. WebRTC is a core plugin, and should be enabled on all cameras.";
}
