# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: koush <koush@koushikdutta.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "doorbird";
  version = "0.0.6";
  hash = "sha512-i6leO7zulJVHQNM0t589IH0xYP4Q8SS4lk7PFvn/p4dnmgQfG8MtciRJwOuYrLx/ypuZBjzdnkPfKiEjQ2ul6Q==";
  meta.description = "Doorbird Plugin - The Doorbird Plugin bridges compatible Doorbird video doorbell cameras to Scrypted.";
}
