# AUTO-GENERATED by plugins-update.sh - do not edit
# Upstream maintainer: billyzoellers <billy.zoellers@mac.com>
{ mkScryptedPlugin }:
mkScryptedPlugin {
  pname = "ecobee";
  version = "0.0.26";
  hash = "sha512-tcNcwI6BL5loBJTtgLDwEDzGChB7U4CHzHR4MTXHGgIuULTocgDnUFGeRYTRoZCB+H2iRLRMwm+fDsojAPSuwQ==";
  passthru = _finalAttrs: { };
  meta.description = "Ecobee Plugin - Ecobee Plugin for Scrypted";
}
